# Generated by Django 5.1.3 on 2024-11-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_rename_customer_name_invoice_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='unit_price',
            new_name='price',
        ),
    ]
