# Generated by Django 5.1.3 on 2024-11-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_client_invoice_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='number',
            new_name='invoice_number',
        ),
    ]
